/**
 * Rails.gs — the gates. This file is the reason you can leave the agent running.
 *
 * Do not edit this file to make a run succeed. If a rail stops you, the rail is
 * right and the intake row or the template is wrong.
 */

var Rails = (function () {
  /**
   * Every {{PLACEHOLDER}} in a string of text.
   */
  function placeholdersIn(text) {
    var found = {};
    var re = /\{\{([A-Z0-9_]+)\}\}/g;
    var m;
    while ((m = re.exec(text)) !== null) found[m[1]] = true;
    return Object.keys(found);
  }

  /**
   * Which of these keys has no usable value.
   *
   * A value is usable when it is present and not blank. Zero is a value.
   * Nothing here ever falls back to a default, a similar row, or what is
   * typical. That is the neverInvent rail, and it is enforced here rather
   * than trusted to a prompt.
   */
  function missingValues(keys, values) {
    var missing = [];
    for (var i = 0; i < keys.length; i++) {
      var k = keys[i];
      var v = values[k];
      if (v === undefined || v === null) { missing.push(k); continue; }
      if (typeof v === 'string' && v.trim() === '') { missing.push(k); continue; }
    }
    return missing;
  }

  /**
   * The precheck. Runs before anything is created, ever.
   *
   * Last year's version of this kit checked each template as it filled it. A
   * packet that failed on its fourth document left three documents and a
   * client folder behind, and a half-built packet looks finished. So every
   * template is scanned first, and nothing is written until all of them pass.
   */
  function precheck(required, values) {
    var missing = missingValues(required, values);
    return {
      ok: missing.length === 0,
      missing: missing,
      message: missing.length === 0 ? 'ok' :
        'Nothing was written, and no folder was created. This run needs ' +
        missing.join(', ') + '. Complete the intake row and run it again. ' +
        'Do not invent these values.'
    };
  }

  /**
   * Client-facing mail is drafted, never sent. There is no code path in this
   * repository that sends mail to a client, and that is deliberate: the rail
   * is enforced by what is missing, not by an instruction someone can talk
   * their way around.
   *
   * Internal alerts to your own firm are a different thing, and they are off
   * until you turn them on and name your own domains.
   */
  function assertNotifyAllowed(recipient, rails) {
    if (!rails || rails.allowInternalNotify !== true) {
      throw new Error(
        'notify is disabled. Set rails.allowInternalNotify to true and list ' +
        'your firm domains in rails.internalDomains to turn it on.');
    }
    var domains = (rails.internalDomains || []).map(function (d) {
      return String(d).toLowerCase();
    });
    var at = String(recipient).lastIndexOf('@');
    var domain = at === -1 ? '' : String(recipient).slice(at + 1).toLowerCase();
    if (domains.indexOf(domain) === -1) {
      throw new Error(
        'notify refused: ' + recipient + ' is not on an internal domain. ' +
        'Internal alerts may only go to ' + (domains.join(', ') || '(none configured)') +
        '. Mail to a client is drafted, never sent.');
    }
    return true;
  }

  /**
   * Outbound HTTP. This is the rail that matters most once an agent can talk
   * to the internet, because this is where client data leaves the firm.
   *
   * Off until you turn it on and name the hosts you meant. An allowlist of
   * exact hostnames, never a wildcard, never "any https".
   */
  function assertOutboundAllowed(url, rails) {
    if (!rails || rails.allowOutboundHttp !== true) {
      throw new Error(
        'httpRequest is disabled. Set rails.allowOutboundHttp to true and list ' +
        'the hosts you meant in rails.allowedHosts to turn it on.');
    }
    var host = String(url).replace(/^https?:\/\//i, '').split('/')[0].split(':')[0].toLowerCase();
    if (!/^https:\/\//i.test(String(url))) {
      throw new Error('httpRequest refused: ' + url + ' is not https.');
    }
    var allowed = (rails.allowedHosts || []).map(function (h) { return String(h).toLowerCase(); });
    if (allowed.indexOf(host) === -1) {
      throw new Error(
        'httpRequest refused: ' + host + ' is not on the allowlist. ' +
        'Allowed: ' + (allowed.join(', ') || '(none configured)') + '.');
    }
    return true;
  }

  /**
   * Drive query strings are single quoted, so an apostrophe in a client's name
   * breaks the query. A client named O'Donnell found this the hard way.
   * Every query in this kit goes through here.
   */
  function escapeQuery(value) {
    return String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  }

  return {
    placeholdersIn: placeholdersIn,
    missingValues: missingValues,
    precheck: precheck,
    assertNotifyAllowed: assertNotifyAllowed,
    assertOutboundAllowed: assertOutboundAllowed,
    escapeQuery: escapeQuery
  };
})();

if (typeof module !== 'undefined') module.exports = Rails;
