/**
 * Runner.gs — the engine. You do not edit this file.
 *
 * It does the same six things every time, in the same order, for every row:
 * claim it, check it can be done, do the steps, write back, log, stop.
 *
 * Everything specific to your firm lives in Config.gs.
 */

var Runner = (function () {

  /* ---------- sheet access ---------- */

  function sheet_() {
    var cfg = CONFIG.intake;
    var ss = SpreadsheetApp.openById(cfg.sheetId);
    var sh = ss.getSheetByName(cfg.tabName);
    if (!sh) throw new Error('No tab named "' + cfg.tabName + '" in that spreadsheet.');
    return sh;
  }

  /**
   * A column header becomes a placeholder key: upper case, non alphanumerics
   * become underscores. "client name" and "client_name" both become
   * CLIENT_NAME. This is the whole contract between your sheet and your
   * templates.
   */
  function keyForHeader(header) {
    return String(header).trim().toUpperCase().replace(/[^A-Z0-9]+/g, '_').replace(/^_+|_+$/g, '');
  }

  function readTable_() {
    var sh = sheet_();
    var range = sh.getDataRange();
    var grid = range.getValues();
    if (grid.length < 1) return { headers: [], rows: [], sheet: sh };
    var headers = grid[0].map(function (h) { return String(h).trim(); });
    var rows = [];
    for (var r = 1; r < grid.length; r++) {
      var byHeader = {};
      var blank = true;
      for (var c = 0; c < headers.length; c++) {
        if (!headers[c]) continue;
        var v = grid[r][c];
        byHeader[headers[c]] = v;
        if (String(v).trim() !== '') blank = false;
      }
      if (blank) continue;
      rows.push({ rowNumber: r + 1, byHeader: byHeader });
    }
    return { headers: headers, rows: rows, sheet: sh };
  }

  function columnIndex_(headers, name) {
    var wanted = keyForHeader(name);
    for (var i = 0; i < headers.length; i++) {
      if (keyForHeader(headers[i]) === wanted) return i + 1;
    }
    return -1;
  }

  /* ---------- values ---------- */

  function valuesFor_(row, headers) {
    var values = {};
    Object.keys(CONFIG.profile || {}).forEach(function (k) {
      values[k] = CONFIG.profile[k];
    });
    headers.forEach(function (h) {
      if (!h) return;
      var raw = row.byHeader[h];
      values[keyForHeader(h)] = formatValue_(raw);
    });
    values._NOW = nowString_();
    return values;
  }

  function formatValue_(v) {
    if (v instanceof Date) {
      return Utilities.formatDate(v, CONFIG.timezone || Session.getScriptTimeZone(),
        CONFIG.dateFormat || 'MMMM d, yyyy');
    }
    return v;
  }

  function nowString_() {
    return Utilities.formatDate(new Date(), CONFIG.timezone || Session.getScriptTimeZone(),
      'yyyy-MM-dd HH:mm');
  }

  /* ---------- logging ---------- */

  function log_(id, status, detail) {
    var tab = (CONFIG.logging && CONFIG.logging.tabName) || 'Log';
    var ss = SpreadsheetApp.openById(CONFIG.intake.sheetId);
    var sh = ss.getSheetByName(tab);
    if (!sh) {
      sh = ss.insertSheet(tab);
      sh.appendRow(['when', 'id', 'status', 'detail']);
    }
    sh.appendRow([nowString_(), id, status, detail]);
  }

  /* ---------- one row ---------- */

  function processRow_(row, headers, sheet) {
    var cfg = CONFIG.intake;
    var statusCol = columnIndex_(headers, cfg.statusColumn);
    if (statusCol === -1) throw new Error('No "' + cfg.statusColumn + '" column in the intake sheet.');

    var idCol = columnIndex_(headers, cfg.idColumn);
    var id = idCol === -1 ? ('row ' + row.rowNumber) : String(row.byHeader[headers[idCol - 1]]);

    var values = valuesFor_(row, headers);

    function setStatus(v) {
      sheet.getRange(row.rowNumber, statusCol).setValue(v);
      SpreadsheetApp.flush();
    }

    function setCell(columnName, value) {
      var c = columnIndex_(headers, columnName);
      if (c === -1) return false;
      sheet.getRange(row.rowNumber, c).setValue(value);
      return true;
    }

    // 1. Claim it, before any work. Two runs must never hold the same row.
    setStatus(cfg.workingValue || 'Processing');

    var ctx = {
      id: id,
      values: values,
      config: CONFIG,
      documents: [],
      pdfs: [],
      reviewFindings: [],
      folder: null,
      setCell: setCell,
      ensureFolder: function () {
        if (ctx.folder) return ctx.folder;
        var parent = DriveApp.getFolderById(CONFIG.output.documentsFolderId);
        var name = Steps.render(CONFIG.output.folderNameFormat || '{{' + keyForHeader(cfg.idColumn) + '}}', values);
        // One folder per run, created once, before any fan out. Four workers
        // each checking "does it exist" and then creating it gave us four
        // identical folders the first time this pattern ran.
        var existing = parent.getFoldersByName(name);
        ctx.folder = existing.hasNext() ? existing.next() : parent.createFolder(name);
        values._FOLDER_URL = ctx.folder.getUrl();
        values._FOLDER_ID = ctx.folder.getId();
        return ctx.folder;
      }
    };

    // 2. Precheck every step before the first write.
    var required = [];
    (CONFIG.steps || []).forEach(function (step) {
      Steps.requiredKeysFor(step, CONFIG).forEach(function (k) { required.push(k); });
    });
    var gate = Rails.precheck(required, values);
    if (!gate.ok) {
      setStatus(cfg.needsInfoValue || 'Needs info');
      setCell(cfg.reasonColumn || 'notes', gate.message);
      log_(id, 'REFUSED', 'missing: ' + gate.missing.join(', ') + '. Nothing written.');
      return { id: id, status: 'refused', missing: gate.missing, message: gate.message };
    }

    // 3. The steps, in the order you declared them.
    var results = [];
    try {
      (CONFIG.steps || []).forEach(function (step) {
        var fn = Steps[step.type];
        if (typeof fn !== 'function') throw new Error('Unknown step type: ' + step.type);
        results.push({ step: step.type, result: fn(step, ctx) });
      });
    } catch (err) {
      setStatus(err.reviewFailed ? (cfg.failedValue || 'Needs attention') : (cfg.failedValue || 'Needs attention'));
      setCell(cfg.reasonColumn || 'notes', String(err.message).slice(0, 480));
      log_(id, 'FAILED', String(err.message).slice(0, 480));
      return { id: id, status: 'failed', error: String(err.message) };
    }

    // 4. Done. The row says so, and the log says what happened.
    setStatus(cfg.doneValue || 'Done');
    log_(id, 'OK', ctx.documents.length + ' document(s)' +
      (ctx.draftId ? ', email drafted, not sent' : '') +
      (ctx.folder ? ', folder ' + ctx.folder.getName() : ''));

    return {
      id: id,
      status: 'ok',
      documents: ctx.documents.map(function (d) { return d.name; }),
      folderUrl: values._FOLDER_URL || null,
      draftCreated: !!ctx.draftId,
      steps: results
    };
  }

  /* ---------- entry points ---------- */

  /**
   * Check the sheet once, do whatever is ready, stop. This is what the
   * time-driven trigger calls.
   */
  function runOnce() {
    var lock = LockService.getScriptLock();
    if (!lock.tryLock(10000)) {
      return { ran: 0, note: 'another run holds the lock' };
    }
    try {
      var table = readTable_();
      var cfg = CONFIG.intake;
      var ready = table.rows.filter(function (r) {
        var v = r.byHeader[headerNamed_(table.headers, cfg.statusColumn)];
        return String(v).trim() === String(cfg.readyValue).trim();
      });

      var limit = CONFIG.maxPerRun || 5;
      var done = [];
      for (var i = 0; i < ready.length && i < limit; i++) {
        done.push(processRow_(ready[i], table.headers, table.sheet));
      }
      if (done.length === 0) Logger.log('nothing new');
      return { ran: done.length, results: done };
    } finally {
      lock.releaseLock();
    }
  }

  function headerNamed_(headers, name) {
    var idx = columnIndex_(headers, name);
    return idx === -1 ? name : headers[idx - 1];
  }

  return {
    runOnce: runOnce,
    keyForHeader: keyForHeader,
    readTable_: readTable_,
    processRow_: processRow_,
    columnIndex_: columnIndex_,
    log_: log_
  };
})();

/** The function your trigger calls. Keep this name. */
function runOnce() {
  return Runner.runOnce();
}

if (typeof module !== 'undefined') module.exports = Runner;
